/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  env: {
    ADMIN_ADDRESS: process.env.ADMIN_ADDRESS || process.env.NEXT_PUBLIC_ADMIN_ADDRESS,
    NEXT_PUBLIC_ADMIN_ADDRESS: process.env.NEXT_PUBLIC_ADMIN_ADDRESS || process.env.ADMIN_ADDRESS,
    NETWORK_URL: process.env.NETWORK_URL || process.env.NEXT_PUBLIC_NETWORK_URL,
    NEXT_PUBLIC_NETWORK_URL: process.env.NEXT_PUBLIC_NETWORK_URL || process.env.NETWORK_URL,
    CHAIN_ID: process.env.CHAIN_ID || process.env.NEXT_PUBLIC_CHAIN_ID,
    NEXT_PUBLIC_CHAIN_ID: process.env.NEXT_PUBLIC_CHAIN_ID || process.env.CHAIN_ID,
    IDENTITY_CONTRACT_ADDRESS: process.env.IDENTITY_CONTRACT_ADDRESS || process.env.NEXT_PUBLIC_IDENTITY_CONTRACT_ADDRESS,
    NEXT_PUBLIC_IDENTITY_CONTRACT_ADDRESS: process.env.NEXT_PUBLIC_IDENTITY_CONTRACT_ADDRESS || process.env.IDENTITY_CONTRACT_ADDRESS,
    CERTIFICATES_CONTRACT_ADDRESS: process.env.CERTIFICATES_CONTRACT_ADDRESS || process.env.NEXT_PUBLIC_CERTIFICATES_CONTRACT_ADDRESS,
    NEXT_PUBLIC_CERTIFICATES_CONTRACT_ADDRESS: process.env.NEXT_PUBLIC_CERTIFICATES_CONTRACT_ADDRESS || process.env.CERTIFICATES_CONTRACT_ADDRESS,
    EXAMINATIONS_CONTRACT_ADDRESS: process.env.EXAMINATIONS_CONTRACT_ADDRESS || process.env.NEXT_PUBLIC_EXAMINATIONS_CONTRACT_ADDRESS,
    NEXT_PUBLIC_EXAMINATIONS_CONTRACT_ADDRESS: process.env.NEXT_PUBLIC_EXAMINATIONS_CONTRACT_ADDRESS || process.env.EXAMINATIONS_CONTRACT_ADDRESS,
    SECURITY_UTILS_CONTRACT_ADDRESS: process.env.SECURITY_UTILS_CONTRACT_ADDRESS || process.env.NEXT_PUBLIC_SECURITY_UTILS_CONTRACT_ADDRESS,
    NEXT_PUBLIC_SECURITY_UTILS_CONTRACT_ADDRESS: process.env.NEXT_PUBLIC_SECURITY_UTILS_CONTRACT_ADDRESS || process.env.SECURITY_UTILS_CONTRACT_ADDRESS,
    EXAM_MANAGEMENT_CONTRACT_ADDRESS: process.env.EXAM_MANAGEMENT_CONTRACT_ADDRESS || process.env.NEXT_PUBLIC_EXAM_MANAGEMENT_CONTRACT_ADDRESS,
    NEXT_PUBLIC_EXAM_MANAGEMENT_CONTRACT_ADDRESS: process.env.NEXT_PUBLIC_EXAM_MANAGEMENT_CONTRACT_ADDRESS || process.env.EXAM_MANAGEMENT_CONTRACT_ADDRESS,
  },
  webpack: (config) => {
    config.resolve.fallback = { fs: false, net: false, tls: false };
    return config;
  },
  experimental: {
    forceSwcTransforms: true,
  },
  serverRuntimeConfig: {
    mySecret: process.env.NEXTAUTH_SECRET,
  },
  publicRuntimeConfig: {
    staticFolder: '/static',
  }
} 